app/Core/erp/urls.py
from django.urls import path
from Core.erp.views.dashboard.views import *
from Core.erp.views.huawei.views import *
from Core.erp.views.mantenimiento.sitio.views import *
from Core.erp.views.mantenimiento.aplicacion.views import *
from Core.erp.views.mantenimiento.tipoProceso.views import *
from Core.erp.views.mantenimiento.tipoArchivoCarga.views import *
from Core.erp.views.wireless.views import *



app_name = 'erp'

urlpatterns = [
    #mantenimiento
    path('mantenimient/sitio/lista', SitioListView.as_view(), name='lista_sitio'),
    path('mantenimient/aplicacion/lista', AplicacionListView.as_view(), name='lista_aplicacion'),
    path('mantenimient/tipoProceso/lista', TipoProcesoListView.as_view(), name='lista_tipoProceso'),
    path('mantenimient/tipoArchivoCarga/lista', TipoArchivoCargaListView.as_view(), name='lista_tipoArchivo'),
    #huawei
    path('huawei/lista/', HuaweiArchivoListView.as_view(), name='lista_archivoHuawei'),

    #wireless
    path('wireless/lista/', WirelessArchivoListView.as_view(), name='lista_archivoWireless'),

    #home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

]

app/Core/user/urls.py
from django.urls import path
from Core.user.views import *

app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from Core.erp.urls import *
from Core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('Core.erp.urls')),
    path('user/', include('Core.user.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/vtc/body.html
{% extends 'home.html' %}
{% load static %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed text-sm">
      <div class="loader" style="display:none">
        <div class="cssload-container">
            <div class="cssload-speeding-wheel"></div>
        </div>
       </div>
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                           <!-- <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>-->
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'erp:dashboard' %}"> <i class="fas fa-home"></i> Inicio</a></li>
                                <li class="breadcrumb-item"><a href="#">{{ project }}</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}


    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

{% block scriptLoad %}
    <script src="{% static 'js/Load.js' %}"></script>
    <script>
     $(document).ready(function () {
        load.init();
     });
    </script>
{% endblock %}

app/templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark color_herder">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">  <i class="fas fa-home"></i> Inicio</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
     <li class="nav-item dropdown">
              <span class="dropdown-header" style="font-size: 12px; color:white">
                        Su último acceso fue {{ request.user.last_login }}
              </span>
     </li>
        {% if request.user.groups.all %}


            <li class="nav-item dropdown">

                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown" style="display: none">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

app/templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'erp:dashboard' %}" class="brand-link">
       <img src="{% static 'img/logo_ipt.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">IPT</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static  'img/user.png' %}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block" style="text-transform: uppercase">{{ request.user.username }}</a>
                <ul class="ml-0 mb-0 fa-ul text-muted">
                    <li class="small"><span class="fa-li"></span> {{ request.user.email }} </li>
                </ul>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                 <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Mantenimiento
                            <i class="right fas fa-angle-left"></i>
                        </p>

                    </a>
                        <ul class="nav nav-treeview">
                              <li class="nav-item">
                                <a href="{% url 'erp:lista_sitio' %}" class="nav-link">
                                  <i class="fa fa-circle nav-icon-perso"></i>
                                  <p> Sitios</p>
                                </a>
                              </li>
                              <li class="nav-item">
                                <a href="{% url 'erp:lista_aplicacion' %}" class="nav-link">
                                  <i class="fa fa-circle nav-icon-perso"></i>
                                  <p> Aplicaciones</p>
                                </a>
                              </li>

                              <li class="nav-item">
                                <a href="{% url 'erp:lista_tipoProceso' %}" class="nav-link">
                                  <i class="fa fa-circle nav-icon-perso"></i>
                                  <p> Tipo de proceso</p>
                                </a>
                              </li>

                               <li class="nav-item">
                                <a href="{% url 'erp:lista_tipoArchivo' %}" class="nav-link">
                                  <i class="fa fa-circle nav-icon-perso"></i>
                                  <p> Tipo de archivo</p>
                                </a>
                              </li>
                        </ul>

                 </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-mobile-alt"></i>
                        <p>
                            HUAWEI
                            <i class="right fas fa-angle-left"></i>
                        </p>

                    </a>
                        <ul class="nav nav-treeview">
                              <li class="nav-item">
                                <a href="{% url 'erp:lista_archivoHuawei' %}" class="nav-link">
                                  <i class="fa fa-upload nav-icon-perso"></i>
                                  <p>Carga de archivo</p>
                                </a>
                              </li>
                              <li class="nav-item" style="display: none">
                                <a href="#" class="nav-link">
                                  <i class="fa fa-check-double nav-icon-perso"></i>
                                  <p>Validar 2</p>
                                </a>
                              </li>
                        </ul>

                 </li>

                <li class="nav-item">

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-mobile-alt"></i>
                        <p>
                            WIRELESS

                            <i class="right fas fa-angle-left"></i>
                        </p>

                    </a>
                        <ul class="nav nav-treeview">
                              <li class="nav-item">
                                <a href="{% url 'erp:lista_archivoWireless' %}" class="nav-link">
                                  <i class="fa fa-upload nav-icon-perso"></i>
                                  <p>Carga de archivo</p>
                                </a>
                              </li>
                              <li class="nav-item" style="display: none">
                                <a href="#" class="nav-link">
                                  <i class="fa fa-check-double nav-icon-perso"></i>
                                  <p>Validar 2</p>
                                </a>
                              </li>
                        </ul>

                 </li>


                <li class="nav-item">
                    <a href="{% url 'user:user_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-user-friends"></i>
                        <p>
                            Usuarios
                        </p>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</aside>